#pragma once
#include"AirWeapon.h"
#include"AllMovableObjects.h"
#include"Ammo.h"
#include"AntiAir.h"
#include"Attacker.h"
#include"Bomb.h"
#include"BombLoader.h"
#include"Camera.h"
#include"DefinedData.h"
#include"Lock.h"
#include"Morale.h"
#include"PictureLoader.h"
#include"Plane.h"
#include"ShipCrashParts.h"
#include"Torpedo.h"
#include"TorpedoLoader.h"
#include"Weapon.h"

#include"DxLib.h"